config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'

  get '/lessons', to: 'lessons#list'
  resources :lessons do
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/craft.rb
class Craft < ApplicationRecord
  belongs_to :lesson
end

app/models/exercise.rb
class Exercise < ApplicationRecord
end

app/models/homework.rb
class Homework < ApplicationRecord
  belongs_to :lesson
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  has_one :craft
  has_one :exercise
  has_one :homework
  has_one :preface
  has_one :primary
  accepts_nested_attributes_for :preface
  accepts_nested_attributes_for :primary
  accepts_nested_attributes_for :exercise
  accepts_nested_attributes_for :homework
end

app/models/preface.rb
class Preface < ApplicationRecord
  has_many :sections
  has_one :lesson

  accepts_nested_attributes_for :sections
end

app/models/primary.rb
class Primary < ApplicationRecord
  has_many :sections
  belongs_to :lesson

  accepts_nested_attributes_for :sections
end

app/models/section.rb
class Section < ApplicationRecord
  belongs_to :preface
  belongs_to :primary
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController

  def new
    @lesson = Lesson.new
    @homework = Homework.new
  end

  def edit
    @lesson = Lesson.find(params[:id])
  end

  def create
    Lesson.create(lesson_attributes)
    render 'welcome/index'
  end

  def update
    Lesson.find(params[:id]).update_attributes(lesson_attributes)
    render 'welcome/index'
  end

  def destroy
    @lesson = Lesson.find(params[:id])
    if @lesson.destroy
      flash[:success] = "Урокът #{@lesson.name} е заличен"
    else
      flash[:error] = "Урокът #{@lesson.name} не може да бъде заличен"
    end
  end

  def list
    @title = 'Уроци'
    @lessons = Lesson.all.order(updated_at: :desc)
    render 'list'
  end

  def show
    @lesson = Lesson.find(params[:id])
    @title = "Урок #{@lesson.name}"
  end

  def lesson_attributes
    params
      .require(:lesson)
      .permit(:group, homework: [:content],
              exercise: [:content],
              preface:
                [:"length(1i)", :"length(2i)", :"length(3i)", :"length(4i)", :"length(5i)", :description, :content],
              primary:
                [:"length(1i)", :"length(2i)", :"length(3i)", :"length(4i)", :"length(5i)", :description, :content, sections: []]
             )
  end
end

app/controllers/welcome_controller.rb
# coding: utf-8
class WelcomeController < ApplicationController
  def index
    @title = 'Пътуващото училище на Подарете книга'
    render 'index'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @title || 'Vygotsky' %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lessons/_form.html.haml
= form_for @lesson do |f|
  = f.label :group
  = f.text_field :group

  %h3 Увод
  = f.fields_for :preface do |preface_form|
    %p
      = preface_form.label :length
      = preface_form.time_select :length
    %p
      = preface_form.label :description
      = preface_form.text_field :description

      = render partial: 'section_form', locals: { form: preface_form }


  %h3 Основна част
  = f.fields_for :primary do |primary_form|
    %p
      = primary_form.label :length
      = primary_form.time_select :length
    %p
      = primary_form.label :description
      = primary_form.text_field :description

      = render partial: 'section_form', locals: { form: primary_form }

  %h3 Упражнение
  = f.fields_for :exercise do |exercise_form|
    %p
      = exercise_form.label :content
      = exercise_form.text_area :content

  %h3 Домашна работа
  = f.fields_for :homework do |homework_form|
    %p
      = homework_form.label :content
      = homework_form.text_area :content

  = f.submit

app/views/lessons/_section_form.html.haml
%p
  = form.label :content
  = form.text_area :content

app/views/lessons/edit.html.haml
= render partial: '/welcome/menu'

= render partial: 'form'

app/views/lessons/list.html.haml
= render partial: '/welcome/menu'

%div{style: 'margin: 10px 0px 0px 30px;'}
  - @lessons.each do |lesson|
    %p{style: 'margin: 40px 0px 30px'}
      = link_to lesson.name, lesson_path(lesson), style: 'background-color: #f79102; color: white; padding: 10px 20px 10px 20px; border-radius: 10px; font-size: 20px'#, target: '_blank'

app/views/lessons/new.html.haml
= render partial: '/welcome/menu'

= form_for @lesson do |f|
  = f.submit

app/views/lessons/show.html.haml
= render partial: '/welcome/menu'

= render partial: 'form'

app/views/welcome/_menu.html.haml
%div#menu
  %div.content{style: 'padding-left: 155px;'}
    %div#logo
      %a(href='http://podarivreme.org/')
        %img(src='http://podarivreme.org/images/interface/logo.png')
    %ul.no-list
      %li
        %a(href="http://podarivreme.org/calendar#data_content")КАЛЕНДАР
      %li
        %a(href="http://podarivreme.org/naruchnik")НАРЪЧНИК
      %li
        %a(href="http://podarivreme.org/ieee-istorii")ЙЕЕЕ ИСТОРИИ
      %li
        %a(href="http://podarivreme.org/tursi-se")ТЪРСИ СЕ
      %li
        %a(href="http://podarivreme.org/chat")ЧАТ
        %img(src="http://podarivreme.org/images/interface/chat_icon.png")
%div{style: 'height: 95px; width: 100%;'}

app/views/welcome/index.html.haml
= render partial: '/welcome/menu'

%div{style: 'margin: 10px 0px 0px 30px;'}
  %a{style: 'color: #bf0c00; font-size: 36px;'} Пътуващото училище
%div{style: 'margin: 30px 0px 0px 30px;'}
  %a{style: 'color: #bf0c00; font-size: 22px'} на Подарете книга
  %img{style: 'float: right'}(src='/images/green_tyres_van.png')
%div{style: 'margin: 100px 0px 0px 0px;'}
  = link_to 'Намери урок', '/lessons', style: 'background-color: #bf0c00; color: white; padding: 10px 20px 10px 20px; margin: 30px; border-radius: 10px'
%div{style: 'margin: 100px 0px 0px 0px;'}
  = link_to 'Създай', '/lessons/new', style: 'background-color: #bf0c00; color: white; padding: 10px 20px 10px 20px; margin: 30px; border-radius: 10px'